# Generated by Django 5.2.9 on 2025-12-11 18:17

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('app_unidade_associada', '0005_alter_unidadeassociada_data_insercao'),
        ('auth', '0012_alter_user_first_name_max_length'),
    ]

    operations = [
        migrations.CreateModel(
            name='Usuario',
            fields=[
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('id_usuario', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('nome', models.CharField(max_length=255)),
                ('email', models.EmailField(max_length=254, unique=True, verbose_name='e-mail')),
                ('telefone', models.CharField(blank=True, max_length=15, null=True)),
                ('cpf', models.CharField(blank=True, max_length=14, null=True, unique=True)),
                ('data_cadastro', models.DateField(auto_now_add=True)),
                ('ativo', models.BooleanField(default=True)),
                ('is_staff', models.BooleanField(default=False)),
                ('is_superuser', models.BooleanField(default=False)),
                ('groups', models.ManyToManyField(blank=True, help_text='The groups this user belongs to. A user will get all permissions granted to each of their groups.', related_name='user_set', related_query_name='user', to='auth.group', verbose_name='groups')),
                ('user_permissions', models.ManyToManyField(blank=True, help_text='Specific permissions for this user.', related_name='user_set', related_query_name='user', to='auth.permission', verbose_name='user permissions')),
            ],
            options={
                'verbose_name': 'Usuário',
                'verbose_name_plural': 'Usuários',
                'db_table': 'usuario',
            },
        ),
        migrations.CreateModel(
            name='Colaborador',
            fields=[
                ('id_usuario', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, related_name='colaborador_profile', serialize=False, to=settings.AUTH_USER_MODEL)),
                ('area_atuacao', models.CharField(max_length=100)),
                ('ano_ingresso', models.IntegerField()),
                ('ano_referencia', models.IntegerField()),
                ('ativo_colaborador', models.BooleanField(default=True)),
                ('id_unidade', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='colaboradores_unidade', to='app_unidade_associada.unidadeassociada')),
            ],
            options={
                'db_table': 'colaborador',
                'unique_together': {('id_unidade', 'id_usuario')},
            },
        ),
        migrations.CreateModel(
            name='Coordenador',
            fields=[
                ('id_usuario', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, related_name='coordenador_profile', serialize=False, to=settings.AUTH_USER_MODEL)),
                ('formacao', models.CharField(max_length=100)),
                ('ano_vigencia', models.IntegerField()),
                ('ativo_coordenador', models.BooleanField(default=True)),
                ('id_unidade', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='coordenadores', to='app_unidade_associada.unidadeassociada')),
            ],
            options={
                'db_table': 'coordenador',
                'unique_together': {('id_unidade', 'ano_vigencia')},
            },
        ),
    ]
