# Generated by Django 5.2.9 on 2025-12-11 19:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('usuarios', '0002_alter_usuario_groups_alter_usuario_user_permissions'),
    ]

    operations = [
        migrations.AddField(
            model_name='usuario',
            name='aprovado_coordenador',
            field=models.BooleanField(default=False, verbose_name='Aprovação Coordenador'),
        ),
    ]
