# Generated by Django 5.2.9 on 2025-12-09 22:19

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='UnidadeAssociada',
            fields=[
                ('Id_unidade', models.UUIDField(primary_key=True, serialize=False)),
                ('Nome_unidade', models.TextField(max_length=50)),
                ('Municipio', models.TextField(max_length=255)),
                ('Estado_UF', models.TextField(max_length=2)),
                ('Data_insercao', models.DateField()),
                ('Status', models.BooleanField()),
            ],
        ),
    ]
