# Generated by Django 5.2.9 on 2025-12-09 22:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app_unidade_associada', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='unidadeassociada',
            table='unidade_associada',
        ),
    ]
