# Generated by Django 5.2.9 on 2025-12-10 19:15

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_unidade_associada', '0002_alter_unidadeassociada_table'),
    ]

    operations = [
        migrations.AlterField(
            model_name='unidadeassociada',
            name='Id_unidade',
            field=models.UUIDField(default=uuid.uuid4, primary_key=True, serialize=False),
        ),
    ]
