# Generated by Django 5.2.9 on 2025-12-11 12:56

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_unidade_associada', '0003_alter_unidadeassociada_id_unidade'),
    ]

    operations = [
        migrations.AlterField(
            model_name='unidadeassociada',
            name='Data_insercao',
            field=models.DateField(auto_created=datetime.date(2025, 12, 11)),
        ),
    ]
