# Generated by Django 5.2.9 on 2025-12-11 12:59

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_unidade_associada', '0004_alter_unidadeassociada_data_insercao'),
    ]

    operations = [
        migrations.AlterField(
            model_name='unidadeassociada',
            name='Data_insercao',
            field=models.DateTimeField(auto_created=datetime.datetime.now),
        ),
    ]
